#!/bin/bash

. $(dirname $0)/tags.sh
echo "============== Figuring out all tags for influxdb"
tags=$(tags influxdb)

IMG=$(basename $DOCKER_REPO)
for tag in $tags; do
    btag=$(echo "$tag" | grep "alpine" | grep -v "data" | grep -v "meta" | grep -v "rc")
    if [ -n "$btag" ]; then
        echo "============== Pushing ${IMG}:$btag"
        docker push ${DOCKER_REPO}:$btag
    fi
done
