name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/influx-backup
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/efrecon/influx-backup
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/influx-backup
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/efrecon/influx-backup
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: efrecon/influx-backup
          short-description: Periodical or one-shot raw and CSV backups of Influx databases
